// Token codegen: context/design-tokens.json -> lib/core/theme/tokens.g.dart
//
// Usage:
//   dart run tool/gen_tokens.dart           regenerate tokens.g.dart
//   dart run tool/gen_tokens.dart --check   fail (exit 1) if tokens.g.dart is stale
//
// The JSON file is the single source of truth (synced manually from
// closero-site). This script is the only place allowed to translate token
// values into Dart; `Color(0x...)` may appear only in the generated file.

import 'dart:convert';
import 'dart:io';

const String jsonPath = 'context/design-tokens.json';
const String outPath = 'lib/core/theme/tokens.g.dart';

void main(List<String> args) {
  final check = args.contains('--check');

  final jsonFile = File(jsonPath);
  if (!jsonFile.existsSync()) {
    stderr.writeln('gen_tokens: $jsonPath not found. Run from the repo root.');
    exit(2);
  }
  final source = jsonFile.readAsStringSync();
  final tokens = jsonDecode(source) as Map<String, dynamic>;

  final generated = generate(tokens, fnv1a(source));

  final outFile = File(outPath);
  if (check) {
    if (!outFile.existsSync() || outFile.readAsStringSync() != generated) {
      stderr.writeln(
          'gen_tokens --check: $outPath is stale. Run `dart run tool/gen_tokens.dart` and commit.');
      exit(1);
    }
    stdout.writeln('gen_tokens --check: $outPath is current.');
    return;
  }
  outFile.writeAsStringSync(generated);
  stdout.writeln('gen_tokens: wrote $outPath.');
}

/// FNV-1a 64-bit hash of the JSON source, embedded in the header so the
/// generated file visibly identifies which token snapshot produced it.
String fnv1a(String input) {
  var hash = 0xcbf29ce484222325;
  for (final byte in utf8.encode(input)) {
    hash ^= byte;
    hash = (hash * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF;
  }
  return hash.toRadixString(16).padLeft(16, '0');
}

// ---------------------------------------------------------------------------
// Type scale definition.
//
// design-tokens.json defines the families, the family rule, and the
// letter-spacing rules, but not the per-role sizes; those are fixed here.
// The family is COMPUTED from the rule (18px+ AND bold -> display family),
// never hand-assigned, so a rule-violating entry cannot be generated.
// "Bold" is w600+: the display family only ships 600/700/800 weights.
// ---------------------------------------------------------------------------

class TypeRole {
  const TypeRole(this.name, this.size, this.weight, this.spacingEm, this.color);

  final String name;
  final double size;
  final int weight; // 400/500/600/700/800
  final double spacingEm; // 0 means unset
  final String color; // ClosColors token name
}

// Letter-spacing per the JSON rules: titles -0.02em, buttons -0.01em
// (labelLarge is the button style), uppercase labels 0.05-0.1em.
const List<TypeRole> typeScale = [
  TypeRole('displayLarge', 40, 700, -0.02, 'hi1'),
  TypeRole('displayMedium', 32, 700, -0.02, 'hi1'),
  TypeRole('displaySmall', 28, 700, -0.02, 'hi1'),
  TypeRole('headlineLarge', 24, 700, -0.02, 'hi1'),
  TypeRole('headlineMedium', 20, 700, -0.02, 'hi1'),
  TypeRole('headlineSmall', 18, 700, -0.02, 'hi1'),
  TypeRole('titleLarge', 16, 600, -0.02, 'hi1'),
  TypeRole('titleMedium', 14, 600, -0.02, 'hi2'),
  TypeRole('titleSmall', 13, 600, -0.02, 'hi2'),
  TypeRole('bodyLarge', 16, 400, 0, 'body'),
  TypeRole('bodyMedium', 14, 400, 0, 'body'),
  TypeRole('bodySmall', 12, 400, 0, 'body'),
  TypeRole('labelLarge', 14, 700, -0.01, 'hi1'),
  TypeRole('labelMedium', 12, 500, 0.05, 'mid'),
  TypeRole('labelSmall', 10, 500, 0.08, 'mid'),
];

String generate(Map<String, dynamic> tokens, String sourceHash) {
  final colors = tokens['color'] as Map<String, dynamic>;
  final typography = tokens['typography'] as Map<String, dynamic>;
  final spacing = tokens['spacing'] as Map<String, dynamic>;
  final radius = tokens['radius'] as Map<String, dynamic>;
  final layout = tokens['layout'] as Map<String, dynamic>;

  final families = typography['families'] as Map<String, dynamic>;
  final bodyFamily = (families['body'] as Map<String, dynamic>)['value'] as String;
  final displayFamily =
      (families['display'] as Map<String, dynamic>)['value'] as String;

  final spacingScale = (spacing['scale'] as Map<String, dynamic>)
      .map((k, v) => MapEntry(k, (v as num).toDouble()));
  final spacingRules = spacing['rules'] as Map<String, dynamic>;
  final headlineToSubtext =
      spKey(spacingRules['headlineToSubtext'] as String, spacingScale);
  final sectionGap = spKey(spacingRules['sectionToNext'] as String, spacingScale);

  final cardRadius = maxPx(radius['card'] as String);
  final buttonRadius = maxPx(radius['button'] as String);

  final b = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('//')
    ..writeln('// Generated by tool/gen_tokens.dart from $jsonPath.')
    ..writeln('// Source hash (FNV-1a): $sourceHash')
    ..writeln('//')
    ..writeln('// This is the ONLY file in lib/ where Color(0x...) may appear.')
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln();

  writeColors(b, colors);
  writeSpacing(b, spacingScale, headlineToSubtext, sectionGap);
  writeRadius(b, cardRadius, buttonRadius);
  writeLayout(b, layout);
  writeType(b, bodyFamily, displayFamily);

  return b.toString();
}

String spKey(String rule, Map<String, double> scale) {
  final match = RegExp(r'^(sp\d+)').firstMatch(rule);
  if (match == null || !scale.containsKey(match.group(1))) {
    stderr.writeln('gen_tokens: cannot resolve spacing rule "$rule".');
    exit(2);
  }
  return match.group(1)!;
}

/// Parses "5px" or a "5-6px" range (upper bound wins, per the build plan:
/// card 6, button 5).
double maxPx(String raw) {
  final numbers = RegExp(r'\d+')
      .allMatches(raw)
      .map((m) => double.parse(m.group(0)!))
      .toList();
  if (numbers.isEmpty) {
    stderr.writeln('gen_tokens: cannot parse radius "$raw".');
    exit(2);
  }
  return numbers.reduce((a, c) => a > c ? a : c);
}

String hexToDart(String hex, String name) {
  final match = RegExp(r'^#([0-9A-Fa-f]{6})$').firstMatch(hex);
  if (match == null) {
    stderr.writeln('gen_tokens: color "$name" has invalid hex "$hex".');
    exit(2);
  }
  return 'Color(0xFF${match.group(1)!.toUpperCase()})';
}

String fmt(double v) => v == v.roundToDouble() ? v.toStringAsFixed(0) : '$v';

void writeColors(StringBuffer b, Map<String, dynamic> colors) {
  final names = colors.keys.toList();
  b
    ..writeln('/// Color tokens. One field per token in design-tokens.json.')
    ..writeln('class ClosColors extends ThemeExtension<ClosColors> {')
    ..writeln('  const ClosColors({');
  for (final n in names) {
    b.writeln('    required this.$n,');
  }
  b
    ..writeln('  });')
    ..writeln();
  for (final n in names) {
    final entry = colors[n] as Map<String, dynamic>;
    b
      ..writeln('  /// ${entry['usage']}')
      ..writeln('  final Color $n;')
      ..writeln();
  }
  b.writeln('  /// The Bone theme values from design-tokens.json.');
  b.writeln('  static const ClosColors bone = ClosColors(');
  for (final n in names) {
    final entry = colors[n] as Map<String, dynamic>;
    b.writeln('    $n: ${hexToDart(entry['value'] as String, n)},');
  }
  b
    ..writeln('  );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosColors copyWith({');
  for (final n in names) {
    b.writeln('    Color? $n,');
  }
  b.writeln('  }) =>');
  b.writeln('      ClosColors(');
  for (final n in names) {
    b.writeln('        $n: $n ?? this.$n,');
  }
  b
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosColors lerp(ClosColors? other, double t) {')
    ..writeln('    if (other is! ClosColors) return this;')
    ..writeln('    return ClosColors(');
  for (final n in names) {
    b.writeln('      $n: Color.lerp($n, other.$n, t)!,');
  }
  b
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('}')
    ..writeln();
}

void writeSpacing(
  StringBuffer b,
  Map<String, double> scale,
  String headlineToSubtext,
  String sectionGap,
) {
  final names = scale.keys.toList();
  b
    ..writeln('/// Spacing tokens off the 4px scale. Use ONLY these values.')
    ..writeln('class ClosSpacing extends ThemeExtension<ClosSpacing> {')
    ..writeln('  const ClosSpacing();')
    ..writeln();
  for (final n in names) {
    b
      ..writeln('  /// ${fmt(scale[n]!)}px')
      ..writeln('  final double $n = ${fmt(scale[n]!)};')
      ..writeln();
  }
  b
    ..writeln('  /// Headline to subtext gap: $headlineToSubtext '
        '(${fmt(scale[headlineToSubtext]!)}px), always.')
    ..writeln('  double get headlineToSubtext => $headlineToSubtext;')
    ..writeln()
    ..writeln('  /// Section to next section gap: $sectionGap '
        '(${fmt(scale[sectionGap]!)}px), always.')
    ..writeln('  double get sectionGap => $sectionGap;')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosSpacing copyWith() => const ClosSpacing();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosSpacing lerp(ClosSpacing? other, double t) => this;')
    ..writeln('}')
    ..writeln();
}

void writeRadius(StringBuffer b, double card, double button) {
  b
    ..writeln('/// Radius tokens. Full rounding is for circles and progress')
    ..writeln('/// end-caps ONLY (functional), never decoration.')
    ..writeln('class ClosRadius extends ThemeExtension<ClosRadius> {')
    ..writeln('  const ClosRadius();')
    ..writeln()
    ..writeln('  final double card = ${fmt(card)};')
    ..writeln('  final double button = ${fmt(button)};')
    ..writeln('  final double full = 999;')
    ..writeln()
    ..writeln('  BorderRadius get cardRadius => BorderRadius.circular(card);')
    ..writeln('  BorderRadius get buttonRadius => BorderRadius.circular(button);')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosRadius copyWith() => const ClosRadius();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosRadius lerp(ClosRadius? other, double t) => this;')
    ..writeln('}')
    ..writeln();
}

void writeLayout(StringBuffer b, Map<String, dynamic> layout) {
  double numField(String section, String key) {
    final value = (layout[section] as Map<String, dynamic>)[key];
    if (value is! num) {
      stderr.writeln('gen_tokens: layout.$section.$key is not a number.');
      exit(2);
    }
    return value.toDouble();
  }

  final sidebar = (layout['sidebar'] as num).toDouble();
  final coachingPanel = numField('coachingPanel', 'width');
  final collapseBelow = numField('coachingPanel', 'collapseBelow');
  final siteContainer = numField('siteContainer', 'maxWidth');
  final heroColumn = numField('heroColumn', 'maxWidth');

  b
    ..writeln('/// Layout tokens: fixed chrome widths and breakpoints.')
    ..writeln('class ClosLayout extends ThemeExtension<ClosLayout> {')
    ..writeln('  const ClosLayout();')
    ..writeln()
    ..writeln('  /// Expanded sidebar width.')
    ..writeln('  final double sidebar = ${fmt(sidebar)};')
    ..writeln()
    ..writeln('  /// Live-sim coaching panel width.')
    ..writeln('  final double coachingPanel = ${fmt(coachingPanel)};')
    ..writeln()
    ..writeln('  /// Below this viewport width, collapsible chrome')
    ..writeln('  /// (coaching panel, sidebar) collapses.')
    ..writeln('  final double collapseBelow = ${fmt(collapseBelow)};')
    ..writeln()
    ..writeln('  /// Max content container width.')
    ..writeln('  final double siteContainerMaxWidth = ${fmt(siteContainer)};')
    ..writeln()
    ..writeln('  /// Max hero column width.')
    ..writeln('  final double heroColumnMaxWidth = ${fmt(heroColumn)};')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosLayout copyWith() => const ClosLayout();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosLayout lerp(ClosLayout? other, double t) => this;')
    ..writeln('}')
    ..writeln();
}

void writeType(StringBuffer b, String bodyFamily, String displayFamily) {
  b
    ..writeln('/// Type tokens. The scale below is generated THROUGH the family')
    ..writeln('/// rule (18px+ AND bold w600+ -> $displayFamily, everything')
    ..writeln('/// else -> $bodyFamily), so a rule-violating role cannot exist.')
    ..writeln('/// Never override fontFamily per widget; for one-off sizes use')
    ..writeln('/// [ClosType.style], which applies the same rule.')
    ..writeln('class ClosType extends ThemeExtension<ClosType> {')
    ..writeln('  const ClosType();')
    ..writeln()
    ..writeln("  static const String bodyFamily = '$bodyFamily';")
    ..writeln("  static const String displayFamily = '$displayFamily';")
    ..writeln()
    ..writeln('  /// The family rule from design-tokens.json.')
    ..writeln('  static String familyFor(double fontSize, FontWeight weight) =>')
    ..writeln('      fontSize >= 18 && weight.value >= FontWeight.w600.value')
    ..writeln('          ? displayFamily')
    ..writeln('          : bodyFamily;')
    ..writeln()
    ..writeln('  /// Builds a one-off style through the family rule.')
    ..writeln('  /// [letterSpacingEm] follows the token rules: -0.02 titles,')
    ..writeln('  /// -0.01 buttons, 0.05 to 0.1 uppercase labels.')
    ..writeln('  static TextStyle style({')
    ..writeln('    required double fontSize,')
    ..writeln('    required FontWeight weight,')
    ..writeln('    Color? color,')
    ..writeln('    double letterSpacingEm = 0,')
    ..writeln('  }) =>')
    ..writeln('      TextStyle(')
    ..writeln('        fontFamily: familyFor(fontSize, weight),')
    ..writeln('        fontSize: fontSize,')
    ..writeln('        fontWeight: weight,')
    ..writeln('        color: color,')
    ..writeln('        letterSpacing:')
    ..writeln('            letterSpacingEm == 0 ? null : letterSpacingEm * fontSize,')
    ..writeln('      );')
    ..writeln();
  for (final role in typeScale) {
    final weight = 'FontWeight.w${role.weight}';
    final family =
        role.size >= 18 && role.weight >= 600 ? displayFamily : bodyFamily;
    final spacingPx = role.spacingEm * role.size;
    b
      ..writeln('  /// ${fmt(role.size)}px w${role.weight} $family'
          '${role.spacingEm == 0 ? '' : ', ${role.spacingEm}em tracking'}.')
      ..writeln('  TextStyle get ${role.name} => TextStyle(')
      ..writeln("        fontFamily: '$family',")
      ..writeln('        fontSize: ${fmt(role.size)},')
      ..writeln('        fontWeight: $weight,')
      ..writeln('        color: ClosColors.bone.${role.color},');
    if (role.spacingEm != 0) {
      b.writeln('        letterSpacing: $spacingPx,');
    }
    b
      ..writeln('      );')
      ..writeln();
  }
  b.writeln('  TextTheme get textTheme => TextTheme(');
  for (final role in typeScale) {
    b.writeln('        ${role.name}: ${role.name},');
  }
  b
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosType copyWith() => const ClosType();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  ClosType lerp(ClosType? other, double t) => this;')
    ..writeln('}');
}
