// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by tool/gen_tokens.dart from context/design-tokens.json.
// Source hash (FNV-1a): -75d7e826288091a9
//
// This is the ONLY file in lib/ where Color(0x...) may appear.
import 'package:flutter/material.dart';

/// Color tokens. One field per token in design-tokens.json.
class ClosColors extends ThemeExtension<ClosColors> {
  const ClosColors({
    required this.base,
    required this.sidebar,
    required this.surface,
    required this.surface2,
    required this.border,
    required this.border2,
    required this.dim3,
    required this.dim2,
    required this.dim1,
    required this.body,
    required this.mid,
    required this.hi2,
    required this.hi1,
    required this.accent,
    required this.accentDim,
    required this.green,
    required this.warn,
    required this.red,
    required this.destructive,
    required this.onDestructive,
    required this.flame,
  });

  /// Page background
  final Color base;

  /// Sidebar, topbar
  final Color sidebar;

  /// Card surfaces
  final Color surface;

  /// Inset surfaces, icon bg
  final Color surface2;

  /// Primary border
  final Color border;

  /// Secondary border
  final Color border2;

  /// Faintest text, section labels
  final Color dim3;

  /// Inactive nav/icons. NOT body copy (2.09:1)
  final Color dim2;

  /// Tertiary chrome only. NOT body copy (2.37:1)
  final Color dim1;

  /// Secondary body copy (~6.5:1). Use for all real sentences
  final Color body;

  /// Legacy secondary text; prefer body for new copy
  final Color mid;

  /// Active nav, card titles, default bar/chart fill
  final Color hi2;

  /// Primary text
  final Color hi1;

  /// Warm bone. ONLY: primary CTA fill, mic-on control, pricing recommended tier, app icon, income-track gradient end
  final Color accent;

  /// Favicon fill, selection-state left borders, income-track gradient start
  final Color accentDim;

  /// Positive deltas only
  final Color green;

  /// Coaching warn state
  final Color warn;

  /// Coaching miss, destructive text and left borders
  final Color red;

  /// Destructive button fill (solid). Never a tinted wash
  final Color destructive;

  /// Text on destructive fill only
  final Color onDestructive;

  /// Streak flame icon only
  final Color flame;

  /// The Bone theme values from design-tokens.json.
  static const ClosColors bone = ClosColors(
    base: Color(0xFF0E0C0A),
    sidebar: Color(0xFF111009),
    surface: Color(0xFF151210),
    surface2: Color(0xFF1A1714),
    border: Color(0xFF221E1A),
    border2: Color(0xFF2C2824),
    dim3: Color(0xFF36322E),
    dim2: Color(0xFF4A4642),
    dim1: Color(0xFF524E4A),
    body: Color(0xFF9C948A),
    mid: Color(0xFF8A8278),
    hi2: Color(0xFFC8C2BA),
    hi1: Color(0xFFEDE8E3),
    accent: Color(0xFFE8E1D3),
    accentDim: Color(0xFFA39C8E),
    green: Color(0xFF4A9668),
    warn: Color(0xFFC4A840),
    red: Color(0xFFC47878),
    destructive: Color(0xFFB85F5F),
    onDestructive: Color(0xFFFFFFFF),
    flame: Color(0xFFC4915A),
  );

  @override
  ClosColors copyWith({
    Color? base,
    Color? sidebar,
    Color? surface,
    Color? surface2,
    Color? border,
    Color? border2,
    Color? dim3,
    Color? dim2,
    Color? dim1,
    Color? body,
    Color? mid,
    Color? hi2,
    Color? hi1,
    Color? accent,
    Color? accentDim,
    Color? green,
    Color? warn,
    Color? red,
    Color? destructive,
    Color? onDestructive,
    Color? flame,
  }) =>
      ClosColors(
        base: base ?? this.base,
        sidebar: sidebar ?? this.sidebar,
        surface: surface ?? this.surface,
        surface2: surface2 ?? this.surface2,
        border: border ?? this.border,
        border2: border2 ?? this.border2,
        dim3: dim3 ?? this.dim3,
        dim2: dim2 ?? this.dim2,
        dim1: dim1 ?? this.dim1,
        body: body ?? this.body,
        mid: mid ?? this.mid,
        hi2: hi2 ?? this.hi2,
        hi1: hi1 ?? this.hi1,
        accent: accent ?? this.accent,
        accentDim: accentDim ?? this.accentDim,
        green: green ?? this.green,
        warn: warn ?? this.warn,
        red: red ?? this.red,
        destructive: destructive ?? this.destructive,
        onDestructive: onDestructive ?? this.onDestructive,
        flame: flame ?? this.flame,
      );

  @override
  ClosColors lerp(ClosColors? other, double t) {
    if (other is! ClosColors) return this;
    return ClosColors(
      base: Color.lerp(base, other.base, t)!,
      sidebar: Color.lerp(sidebar, other.sidebar, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surface2: Color.lerp(surface2, other.surface2, t)!,
      border: Color.lerp(border, other.border, t)!,
      border2: Color.lerp(border2, other.border2, t)!,
      dim3: Color.lerp(dim3, other.dim3, t)!,
      dim2: Color.lerp(dim2, other.dim2, t)!,
      dim1: Color.lerp(dim1, other.dim1, t)!,
      body: Color.lerp(body, other.body, t)!,
      mid: Color.lerp(mid, other.mid, t)!,
      hi2: Color.lerp(hi2, other.hi2, t)!,
      hi1: Color.lerp(hi1, other.hi1, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      accentDim: Color.lerp(accentDim, other.accentDim, t)!,
      green: Color.lerp(green, other.green, t)!,
      warn: Color.lerp(warn, other.warn, t)!,
      red: Color.lerp(red, other.red, t)!,
      destructive: Color.lerp(destructive, other.destructive, t)!,
      onDestructive: Color.lerp(onDestructive, other.onDestructive, t)!,
      flame: Color.lerp(flame, other.flame, t)!,
    );
  }
}

/// Spacing tokens off the 4px scale. Use ONLY these values.
class ClosSpacing extends ThemeExtension<ClosSpacing> {
  const ClosSpacing();

  /// 4px
  final double sp1 = 4;

  /// 8px
  final double sp2 = 8;

  /// 12px
  final double sp3 = 12;

  /// 16px
  final double sp4 = 16;

  /// 20px
  final double sp5 = 20;

  /// 24px
  final double sp6 = 24;

  /// 32px
  final double sp8 = 32;

  /// 40px
  final double sp10 = 40;

  /// 48px
  final double sp12 = 48;

  /// 64px
  final double sp16 = 64;

  /// 80px
  final double sp20 = 80;

  /// 96px
  final double sp24 = 96;

  /// Headline to subtext gap: sp3 (12px), always.
  double get headlineToSubtext => sp3;

  /// Section to next section gap: sp6 (24px), always.
  double get sectionGap => sp6;

  @override
  ClosSpacing copyWith() => const ClosSpacing();

  @override
  ClosSpacing lerp(ClosSpacing? other, double t) => this;
}

/// Radius tokens. Full rounding is for circles and progress
/// end-caps ONLY (functional), never decoration.
class ClosRadius extends ThemeExtension<ClosRadius> {
  const ClosRadius();

  final double card = 6;
  final double button = 5;
  final double full = 999;

  BorderRadius get cardRadius => BorderRadius.circular(card);
  BorderRadius get buttonRadius => BorderRadius.circular(button);

  @override
  ClosRadius copyWith() => const ClosRadius();

  @override
  ClosRadius lerp(ClosRadius? other, double t) => this;
}

/// Type tokens. The scale below is generated THROUGH the family
/// rule (18px+ AND bold w600+ -> Bricolage Grotesque, everything
/// else -> Figtree), so a rule-violating role cannot exist.
/// Never override fontFamily per widget; for one-off sizes use
/// [ClosType.style], which applies the same rule.
class ClosType extends ThemeExtension<ClosType> {
  const ClosType();

  static const String bodyFamily = 'Figtree';
  static const String displayFamily = 'Bricolage Grotesque';

  /// The family rule from design-tokens.json.
  static String familyFor(double fontSize, FontWeight weight) =>
      fontSize >= 18 && weight.value >= FontWeight.w600.value
          ? displayFamily
          : bodyFamily;

  /// Builds a one-off style through the family rule.
  /// [letterSpacingEm] follows the token rules: -0.02 titles,
  /// -0.01 buttons, 0.05 to 0.1 uppercase labels.
  static TextStyle style({
    required double fontSize,
    required FontWeight weight,
    Color? color,
    double letterSpacingEm = 0,
  }) =>
      TextStyle(
        fontFamily: familyFor(fontSize, weight),
        fontSize: fontSize,
        fontWeight: weight,
        color: color,
        letterSpacing:
            letterSpacingEm == 0 ? null : letterSpacingEm * fontSize,
      );

  /// 40px w700 Bricolage Grotesque, -0.02em tracking.
  TextStyle get displayLarge => TextStyle(
        fontFamily: 'Bricolage Grotesque',
        fontSize: 40,
        fontWeight: FontWeight.w700,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.8,
      );

  /// 32px w700 Bricolage Grotesque, -0.02em tracking.
  TextStyle get displayMedium => TextStyle(
        fontFamily: 'Bricolage Grotesque',
        fontSize: 32,
        fontWeight: FontWeight.w700,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.64,
      );

  /// 28px w700 Bricolage Grotesque, -0.02em tracking.
  TextStyle get displaySmall => TextStyle(
        fontFamily: 'Bricolage Grotesque',
        fontSize: 28,
        fontWeight: FontWeight.w700,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.56,
      );

  /// 24px w700 Bricolage Grotesque, -0.02em tracking.
  TextStyle get headlineLarge => TextStyle(
        fontFamily: 'Bricolage Grotesque',
        fontSize: 24,
        fontWeight: FontWeight.w700,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.48,
      );

  /// 20px w700 Bricolage Grotesque, -0.02em tracking.
  TextStyle get headlineMedium => TextStyle(
        fontFamily: 'Bricolage Grotesque',
        fontSize: 20,
        fontWeight: FontWeight.w700,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.4,
      );

  /// 18px w700 Bricolage Grotesque, -0.02em tracking.
  TextStyle get headlineSmall => TextStyle(
        fontFamily: 'Bricolage Grotesque',
        fontSize: 18,
        fontWeight: FontWeight.w700,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.36,
      );

  /// 16px w600 Figtree, -0.02em tracking.
  TextStyle get titleLarge => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 16,
        fontWeight: FontWeight.w600,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.32,
      );

  /// 14px w600 Figtree, -0.02em tracking.
  TextStyle get titleMedium => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 14,
        fontWeight: FontWeight.w600,
        color: ClosColors.bone.hi2,
        letterSpacing: -0.28,
      );

  /// 13px w600 Figtree, -0.02em tracking.
  TextStyle get titleSmall => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 13,
        fontWeight: FontWeight.w600,
        color: ClosColors.bone.hi2,
        letterSpacing: -0.26,
      );

  /// 16px w400 Figtree.
  TextStyle get bodyLarge => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 16,
        fontWeight: FontWeight.w400,
        color: ClosColors.bone.body,
      );

  /// 14px w400 Figtree.
  TextStyle get bodyMedium => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 14,
        fontWeight: FontWeight.w400,
        color: ClosColors.bone.body,
      );

  /// 12px w400 Figtree.
  TextStyle get bodySmall => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 12,
        fontWeight: FontWeight.w400,
        color: ClosColors.bone.body,
      );

  /// 14px w700 Figtree, -0.01em tracking.
  TextStyle get labelLarge => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 14,
        fontWeight: FontWeight.w700,
        color: ClosColors.bone.hi1,
        letterSpacing: -0.14,
      );

  /// 12px w500 Figtree, 0.05em tracking.
  TextStyle get labelMedium => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 12,
        fontWeight: FontWeight.w500,
        color: ClosColors.bone.mid,
        letterSpacing: 0.6000000000000001,
      );

  /// 10px w500 Figtree, 0.08em tracking.
  TextStyle get labelSmall => TextStyle(
        fontFamily: 'Figtree',
        fontSize: 10,
        fontWeight: FontWeight.w500,
        color: ClosColors.bone.mid,
        letterSpacing: 0.8,
      );

  TextTheme get textTheme => TextTheme(
        displayLarge: displayLarge,
        displayMedium: displayMedium,
        displaySmall: displaySmall,
        headlineLarge: headlineLarge,
        headlineMedium: headlineMedium,
        headlineSmall: headlineSmall,
        titleLarge: titleLarge,
        titleMedium: titleMedium,
        titleSmall: titleSmall,
        bodyLarge: bodyLarge,
        bodyMedium: bodyMedium,
        bodySmall: bodySmall,
        labelLarge: labelLarge,
        labelMedium: labelMedium,
        labelSmall: labelSmall,
      );

  @override
  ClosType copyWith() => const ClosType();

  @override
  ClosType lerp(ClosType? other, double t) => this;
}
